[metadata]
name = sasci360apiworkflow
version = 0.0.1
author = Mark Nelson
author_email = support@nelsongrey.com
description =  Workflow for SAS Customer Intelligence 360
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mnelson3/sas_ci360_api_workflow
project_urls = Bug Tracker = https://github.com/mnelson3/sas_ci360_api_workflow/issues
classifiers = Programming Language :: Python :: 3
	License :: OSI Approved :: Apache Software License
	Operating System :: OS Independent

[options]
package_dir = = src
packages = find:
python_requires = >=3.6
install_requires =
	pandas~=1.4.2
	PyJWT~=2.3.0
	requests~=2.27.1
	saspy~=4.2.0
	schedule~=1.1.0
	DateTime~=4.3
	sasci360apicore~=0.0.1
	urllib3~=1.26.9

[options.packages.find]
where = src
